projects:
  app:
    schemaPath: server/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: server/generated/prisma.graphql
    extensions:
      prisma: server/database/prisma.yml
